cols_i_want = ['CompleteDate',
 'SendingLocationName2',
 'OrderingProvider2',
 'AppointmentLocation',
 'AppointmentCreateDateTime',
 'DesiredAppointmentDate1',
 'AppointmentDateTime',
 'FirstCompleteDateTime',
 'LastActionDate',
 'LastKnownActivityEnteredByStaff',
 'LastKnownActivityComment',
 'Continuous AF in prelim findings(Y/N)',
 'CANScore90Days',
 'Age',
 'PSC',
 'Who was ordering provider (PCP, ED, Cards, Neuro)',
 'Did ordering provider notify Patient',
 'If not, who notified pt',
 'Date Pt Notified',
 'Reason for Study',
 'New AF',
 'Other Significant Findings',
 'Assessment Provided (different than interpretation)',
 'Recommendation provided (change to care plan suggested)',
 'Did cardiologist contact ordering provider directly',
 'Notes',
 'Reviewer']

col_replace_dic = {'CompleteDate':'comp_date', 
   'SendingLocationName2':'send_loc_name',
   'OrderingProvider2':'ordering_provider',
   'AppointmentLocation':"apt_loc",
   'AppointmentCreateDateTime':'apt_create_time',
   'DesiredAppointmentDate1':'apt_time_des',
   'AppointmentDateTime':'apt_time',
   'FirstCompleteDateTime':'comp_time',
   'LastActionDate':'action_date',
   'LastKnownActivityEnteredByStaff':'last_act',
   'LastKnownActivityComment':'last_act_com',
   'Continuous AF in prelim findings(Y/N)':'cont_af',
   'CANScore90Days':'90dcan',
   'Age':"age",
   'PSC':'psc',
   'Who was ordering provider (PCP, ED, Cards, Neuro)':'ord_prov',
   'Did ordering provider notify Patient':'ord_notified',
   'If not, who notified pt':'notifying_party',
   'Date Pt Notified':'date_pt_told',
   'Reason for Study':'reason',
   'New AF':'new_af',
   'Other Significant Findings':'other find',
   'Assessment Provided (different than interpretation)':'assessment',
   'Recommendation provided (change to care plan suggested)':'rec_given',
   'Did cardiologist contact ordering provider directly':'cards_prov_contact',
   'Notes':'notes',
   'Reviewer':'reviewer' 
   }